blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Brandon-Sickler/lumber-tracker-mobile/discussions
    about: Ask questions and discuss ideas with the community
  - name: LinkedIn
    url: https://www.linkedin.com/in/brandonsicklerexpat/
    about: Connect with the project maintainer on LinkedIn
